### PR TITLE
update to 2.5.2

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/tesserocr-feedstock/pull/9

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
> I believe the build is failing after the [new Windows build method (https://github.com/sirfz/tesserocr/blob/master/Windows.build.md) was introduced.

Thanks, will give it a try.

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
Ready for review and merge @conda-forge/tesserocr

**Review by sirfz — APPROVED** [review]

**Pull request merged**
